site_name: 苇下记社
site_description: 个人coclog整合wiki
site_author: 奥丽维娅

theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - footnotes
  - md_in_html   # 允许在 md 文件中写 <style> 和 <div>

docs_dir: docs

nav:
  - 卷封: index.md
  - 档案室: home.md
  - 档案分类: categories.md
  - 驻社名录: roster.md

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js
  - javascripts/glass-sound.js
