site_name: 苇下记社
site_description: 个人coclog整合wiki
site_author: 暗河的奥迪莉亚

theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - footnotes

docs_dir: docs

nav:
  - 卷封: index.md
  - 档案室: home.md
  - 驻社名录: roster.md

#extra_css:
#  - stylesheets/extra.css

#extra_javascript:
#  - javascripts/extra.js
